version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8502"
  redis:
    image: "redis:alpine"
  api:
    build: .
    container_name: api_pdf_ocr
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
