name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fails-fast: false
      matrix:
        os: [ubunto-latest]
        python-version:
            - "3.7"
            - "3.8"
            - "3.9"
            - "3.10"
            - "3.11"
            - "pypy-3.7"
            - "pypy-3.8"
            - "pypy-3.9"

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-puthon@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: bash ./app_test/code_validation.sh
